name: Build and Publish Docker image

on:
  push:
    branches:
      - add-github-actions
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: github-vega-ci-bot-artifacts
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set docker image tag
        id: vars
        run: |
          ref="$(echo -n "${GITHUB_REF#refs/*/}" | tr -c 'A-Za-z0-9._' -)"
          if [[ "$ref" == "main" ]] ; then ref=latest ; fi
          echo ::set-output "name=tag::$ref"

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/notion-data-service:${{ steps.vars.outputs.tag }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
